name: Unit Test for PR

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install dependencies
        run: npm ci
      - name: Run Unit test
        run: |
          ng test --project @irohalab/Deneb-UI --no-watch
        env:
          CHROME_BIN: /usr/bin/google-chrome-stable
